### ISSUE TITLE
COVID NJ County Reports not generating table and graph

### ISSUE THREAD

**Issue by mridulrb** [Call-for-Code/node-red-contrib-twc-covid19-tracker#4]
In the example, Node-RED-covid19-county-dashboard.json tables and graphs are not generated. There is no error generated so I'm not able to understand the issue. 
<img width="1433" alt="COVID_NJ_County_Reports-Dashboard" src="https://user-images.githubusercontent.com/12492961/82139725-0c97f880-983b-11ea-966a-76c5b104af86.png">
<img width="1433" alt="COVID_NJ_County_Reports-Node-RED" src="https://user-images.githubusercontent.com/12492961/82139727-102b7f80-983b-11ea-86ca-046f7b6baf47.png">

**Comment by johnwalicki** [comment]
Hi Mridul - Either your API key assigned by callforcode.weather.com is having problems or you've pasted it in incorrectly.

**Comment by mridulrb** [comment]
Hi John - Update on this issue, the API key was correct. It works locally but not when we deploy Node-Red on OpenShift, I believe there is an issue while retrieving the data from the API on OpenShift but I don't know why is that so. 

<img width="1433" alt="Screen Shot 2020-05-18 at 11 55 38 AM" src="https://user-images.githubusercontent.com/12492961/82188222-9c52ab00-98fe-11ea-9d4e-739836d2abc0.png">

<img width="1433" alt="Screen Shot 2020-05-18 at 12 32 50 PM" src="https://user-images.githubusercontent.com/12492961/82191541-b93dad00-9903-11ea-9724-0e580c3d70e5.png">

**Comment by johnwalicki** [comment]
Interesting...  I've run this flow on Node-RED as a Cloud Foundry web app in IBM Cloud.  I've run Node-RED inside a MiniShift cluster on my local system.  I've not deployed Node-RED on OpenShift on IBM Cloud however.  Not certain why its an issue retrieving data from the TWC API on OpenShift.  It should just make http requests. Would be insightful if you could hit the API using the http request node flow (example 1 in my tutorial).  That would skip the node-red-contrib-twc-covid19-tracker nodes.

**Comment by johnwalicki** [comment]
Let me know if you agree to close the github issue.

**Comment by mridulrb** [comment]
I tried replacing the twc-covid19-tracker node with HTTP Request like example 1 but it didn't work on OpenShift. Locally, it gets data for only 1 county. 
![Screen Shot 2020-05-20 at 5 13 34 PM](https://user-images.githubusercontent.com/12492961/82450054-3eb88d00-9abd-11ea-9854-9d33df1e784a.png)
